<a href="https://colab.research.google.com/github/kirbysmith434/credit-risk-classification/blob/main/credit_risk_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [ ]:
# Import the modules
import pandas as pd
from pathlib import Path

# Define the correct file path
file_path = Path("/content/lending_data.csv")

# Read the data into a Pandas DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to understand the structure
df.head()


loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [ ]:
# Separate the data into labels and features

# Separate the y variable, the labels; Separate the X variable, the features
y = df['loan_status']
X = df.drop('loan_status', axis=1)

# Display the shapes of the separated datasets
print("Labels (y) shape:", y.shape)
print("Features (X) shape:", X.shape)

Labels (y) shape: (77536,)
Features (X) shape: (77536, 7)


In [ ]:
# Review the y variable Series
print(y)


0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64


In [ ]:
# Review the X variable DataFrame
print(X)


       loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                 

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [ ]:
# Check the balance of the labels variable (y)
label_counts = y.value_counts()

# Display the distribution of unique values
print(label_counts)


0    75036
1     2500
Name: loan_status, dtype: int64


### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [ ]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Display the shapes of the training and testing sets
print("Training set shapes - X:", X_train.shape, "y:", y_train.shape)
print("Testing set shapes - X:", X_test.shape, "y:", y_test.shape)



Training set shapes - X: (62028, 7) y: (62028,)
Testing set shapes - X: (15508, 7) y: (15508,)


---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [ ]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_model = LogisticRegression(random_state=1)

# Fit the model using training data
logistic_model.fit(X_train, y_train)


LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [ ]:
# Make predictions using the testing data
y_pred = logistic_model.predict(X_test)
# Display the first few predicted labels
print(y_pred[:10])


[0 0 0 0 0 0 0 0 0 0]


### Step 3: Evaluate the model’s performance by doing the following:

> Indented block



* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [ ]:
from sklearn.metrics import accuracy_score, balanced_accuracy_score, confusion_matrix, classification_report

# Calculate the accuracy score of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy Score: {accuracy:.4f}")

# Calculate the balanced accuracy score of the model
balanced_accuracy = balanced_accuracy_score(y_test, y_pred)
print(f"Balanced Accuracy Score: {balanced_accuracy:.4f}")

Accuracy Score: 0.9922
Balanced Accuracy Score: 0.9521


In [ ]:
# Generate a confusion matrix for the model
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[14926    75]
 [   46   461]]


In [ ]:
# Print the classification report for the model
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15001
           1       0.86      0.91      0.88       507

    accuracy                           0.99     15508
   macro avg       0.93      0.95      0.94     15508
weighted avg       0.99      0.99      0.99     15508



### Step 4: Answer the following question.

[link text](https://)**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** For the label '0' the recall and precision is close to 100%. For the label '1' the precision is about 86%, while the recall is about 91%. The label '0' is the most precise in prediction.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points.

In [ ]:
from imblearn.over_sampling import RandomOverSampler

# Instantiate the RandomOverSampler
ros = RandomOverSampler(random_state=1)

# Resample the data
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

# Confirm the number of data points for each label after resampling
print("After Resampling:")
print("Class distribution in y_resampled:", dict(zip(*np.unique(y_resampled, return_counts=True))))


After Resampling:
Class distribution in y_resampled: {0: 60035, 1: 60035}


In [ ]:
# Count the distinct values of the resampled labels data
distinct_values = y_resampled.value_counts()

# Display the count of each distinct value
print(distinct_values)


0    60035
1    60035
Name: loan_status, dtype: int64


### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [ ]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_model_resampled = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
logistic_model_resampled.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
y_pred_resampled = logistic_model_resampled.predict(X_test)

# Confirm that the model has been fitted
print("Model has been fitted.")

# Display the first few predicted labels
print("First few predicted labels:", y_pred_resampled[:10])



Model has been fitted.
First few predicted labels: [0 0 0 0 0 0 0 0 0 0]


### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [ ]:
from sklearn.metrics import accuracy_score, balanced_accuracy_score, confusion_matrix, classification_report

# Calculate the accuracy score of the model
accuracy_resampled = accuracy_score(y_test, y_pred_resampled)
print(f"Accuracy Score (Resampled): {accuracy_resampled:.4f}")

# Calculate the balanced accuracy score of the model
balanced_accuracy_resampled = balanced_accuracy_score(y_test, y_pred_resampled)
print(f"Balanced Accuracy Score (Resampled): {balanced_accuracy_resampled:.4f}")

# Generate a confusion matrix for the model
conf_matrix_resampled = confusion_matrix(y_test, y_pred_resampled)
print("Confusion Matrix (Resampled):")
print(conf_matrix_resampled)

# Print the classification report for the model
class_report_resampled = classification_report(y_test, y_pred_resampled)
print("Classification Report (Resampled):")
print(class_report_resampled)


Accuracy Score (Resampled): 0.9943
Balanced Accuracy Score (Resampled): 0.9942
Confusion Matrix (Resampled):
[[14915    86]
 [    3   504]]
Classification Report (Resampled):
              precision    recall  f1-score   support

           0       1.00      0.99      1.00     15001
           1       0.85      0.99      0.92       507

    accuracy                           0.99     15508
   macro avg       0.93      0.99      0.96     15508
weighted avg       1.00      0.99      0.99     15508



In [ ]:
from sklearn.metrics import confusion_matrix

# Generate a confusion matrix for the model using the original (unresampled) data
conf_matrix_original = confusion_matrix(y_test, y_pred)

# Display the confusion matrix
print("Confusion Matrix (Original):")
print(conf_matrix_original)


Confusion Matrix (Original):
[[14926    75]
 [   46   461]]


In [ ]:
from sklearn.metrics import classification_report

# Print the classification report for the model using the original (unresampled) data
class_report_original = classification_report(y_test, y_pred)

# Display the classification report
print("Classification Report (Original):")
print(class_report_original)


Classification Report (Original):
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     15001
           1       0.86      0.91      0.88       507

    accuracy                           0.99     15508
   macro avg       0.93      0.95      0.94     15508
weighted avg       0.99      0.99      0.99     15508



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model, trained with oversampled data, exhibits excellent predictive performance for both healthy (0) and high-risk (1) loans, achieving high precision, recall, and F1-scores. The oversampling technique significantly improves the model's ability to identify high-risk loans in the imbalanced dataset.